
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Constants for Supabase connection
const SUPABASE_URL = "https://earqddyjwuassqvgogqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhcnFkZHlqd3Vhc3NxdmdvZ3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTk5MTUsImV4cCI6MjA1NTczNTkxNX0.v3gqCC0Z50623f_T1F0MiVbEWBxF0wIvb9mnPkeOSWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create and export Supabase client for use throughout the application
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
