
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://earqddyjwuassqvgogqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhcnFkZHlqd3Vhc3NxdmdvZ3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTk5MTUsImV4cCI6MjA1NTczNTkxNX0.v3gqCC0Z50623f_T1F0MiVbEWBxF0wIvb9mnPkeOSWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Check if course-media bucket exists - no need to create buckets as they already exist
const verifyBucketsExist = async () => {
  try {
    // Check if course-media bucket exists
    const { data: buckets, error } = await supabase.storage.listBuckets();
    
    const courseBucketExists = buckets?.some(bucket => bucket.name === 'course-media');
    
    if (!courseBucketExists) {
      console.error('Warning: course-media bucket does not exist in Supabase storage');
    } else {
      console.log('Successfully verified course-media bucket exists');
    }
  } catch (error) {
    console.error('Error verifying buckets:', error);
  }
};

// Call the function to verify buckets when this module is loaded
verifyBucketsExist();
